config/routes.rb
Rails.application.routes.draw do
    resources :todo_managers do 
        member do
            patch :complete
        end
    end 

    get 'INDEX', to: 'todo_managers#index'  

    root 'todo_managers#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_manager
end

app/models/todo_manager.rb
class TodoManager < ApplicationRecord
    # Ensuring we dun get empty entries which are useless and clog up space
    has_many :todo_items
    validates :title, presence: true, length: { minimum: 1}
    validates :description, presence: true, length: { minimum: 1}
    validates :deadline, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
    before_action :set_todo_list
    before_action :set_todo_item, except: [:create]
  
    def create
      @todo_item = @todo_manager.todo_items.create(todo_item_params)
      redirect_to @todo_manager
    end
  
    def destroy
      if @todo_item.destroy
        flash[:success] = "Todo List item was deleted."
      else
        flash[:error] = "Todo List item could not be deleted."
      end
      redirect_to @todo_manager
    end
  
    def complete
      @todo_item.update_attribute(:completed_at, Time.now)
      redirect_to @todo_manager, notice: "Todo item completed"
    end
  
    private
  
    def set_todo_list
      @todo_manager = TodoManager.find(params[:todo_manager_id])
    end
  
    def set_todo_item
      @todo_item = @todo_manager.todo_items.find(params[:id])
    end
  
    def todo_item_params
      params[:todo_item].permit(:content)
    end
end

app/controllers/todo_managers_controller.rb
class TodoManagersController < ApplicationController
  before_action :set_todo_manager, only: [:show, :edit, :update, :destroy, :complete]


  # GET /todo_managers
  # GET /todo_managers.json
  def index
    #Search function defined privately below; params[:search] from search_form in index.html.erb
    key_search(params[:search])
  end

  # GET /todo_managers/1
  # GET /todo_managers/1.json
  def show
  end

  # GET /todo_managers/new
  def new
    @todo_manager = TodoManager.new
  end

  # GET /todo_managers/1/edit
  def edit
  end

  # POST /todo_managers
  # POST /todo_managers.json
  def create
    @todo_manager = TodoManager.new(todo_manager_params)

    respond_to do |format|
      if @todo_manager.save
        format.html { redirect_to @todo_manager, notice: 'Todo manager was successfully created.' }
        format.json { render :show, status: :created, location: @todo_manager }
      else
        format.html { render :new }
        format.json { render json: @todo_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_managers/1
  # PATCH/PUT /todo_managers/1.json
  def update
    respond_to do |format|
      if @todo_manager.update(todo_manager_params)
        format.html { redirect_to @todo_manager, notice: 'Todo manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_manager }
      else
        format.html { render :edit }
        format.json { render json: @todo_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_managers/1
  # DELETE /todo_managers/1.json
  def destroy
    @todo_manager.destroy
    respond_to do |format|
      format.html { redirect_to todo_managers_url, notice: 'Todo manager was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def complete
    @todo_manager = TodoManager.find_by_id(params[:id])
    # Checking if task has already been marked as completed 
    if @todo_manager.completed_at
        @todo_manager.update_attributes(:completed_at => false, :completed => false)
    else   
        @todo_manager.update_attributes(:completed_at => DateTime.current, :completed => true)
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_manager
      @todo_manager = TodoManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_manager_params
      params.require(:todo_manager).permit(:title, :description, :search, :tags, :completed_at, :deadline)
    end

    def key_search(search)
        if search #Will return 0 entries if search term is not found; basic SQL querying
            @todo_managers = TodoManager.where("LOWER(title) Like ? OR LOWER(description) LIKE ?", 
            "%#{search.downcase}%", "%#{search.downcase}%")
        else  #Returns all the entries in the model if search term is NIL
            @todo_managers= TodoManager.all
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_managers_helper.rb
module TodoManagersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <div class = "container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_manager, @todo_manager.todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "New Todo" %>
 <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<p><%= todo_item.content %></p>

app/views/todo_managers/_form.html.erb
<%= form_with(model: todo_manager, local: true) do |form| %>
  <% if todo_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_manager.errors.count, "error") %> prohibited this todo item from being saved:</h2>

      <ul>
        <% todo_manager.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tag %>
  </div>

  <div class="field">
  <%= form.label  :"To be completed by" %>
  <%= form.date_field :deadline, as: :date, :placeholder  => 'yyyy/mm/dd', class: 'form-control datepicker' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>


<script>
  $( document ).ready(function() {
    $('.datepicker').datepicker({format: 'dd/mm/yyyy'});
  });
</script>

app/views/todo_managers/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form', todo_manager: @todo_manager %>

<%= link_to 'Show', @todo_manager %> |
<%= link_to 'Back', todo_managers_path %>

app/views/todo_managers/index.html.erb
<!DOCTYPE html>
<STYLE>A {text-decoration: none;} </STYLE>

<div class = "todo_header">
<h1>Todo Manager</h1>
</div>

<h3><%= "Search by keyword" %></h3>
<%= form_tag(todo_managers_path, method: :get, class: 'navbar-form navbar-left') do %>  
 
    <%= text_field_tag(:search, params[:search], placeholder: "Search by Title or Description...", class: "form-control") %> 
    <%= submit_tag ("Search"), :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %> 
<% end %>
<br>

<%
=begin%>
 Raising an error if search term is present and not found 
<%
=end%>
<% if params[:search] and @todo_managers.size == 0 %>
    <div class = "alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
        <strong>Search term not found!</strong> Please refine your search.
    </div>
<% end %>
<br>

<table class = "fixed_header">
<h2>Completed Tasks</h2>
<thead>
    <tr>
    <th>No.</th>  
    <th >Title</th>
    <th>Description</th>
    </tr>
</thead>

<tbody>
    <% count = 1  %>
    <% @todo_managers.each do |todo_manager| %>
    <% if todo_manager.completed %>
    <tr>
        <td><%= count %></td>
        <td><%= todo_manager.title %></td>

        <td><%= todo_manager.description %></td>
        <td><%= link_to 'Show', todo_manager %></td>
        <td><%= link_to 'Edit', edit_todo_manager_path(todo_manager) %></td>
        <td><%= link_to 'Delete', todo_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Mark as Complete', complete_todo_manager_path(todo_manager), method: :patch %></td>
    </tr>
    <% count += 1 %>
    <% end %>
    <% end %>
</tbody>

</table>
<table class = "fixed_header">
<h2>Uncompleted Tasks</h2>
<thead>
    <tr>
    <th>No.</th>  
    <th >Title</th>
    <th>Description</th>
    </tr>
</thead>

<tbody>
    <% count = 1  %>
    <% @todo_managers.each do |todo_manager| %>
    <% if !todo_manager.completed %>

    <tr>
        <td><%= count %></td>
        <td><%= todo_manager.title %></td>

        <td><%= todo_manager.description %></td>
        <td><%= link_to 'Show', todo_manager %></td>
        <td><%= link_to 'Edit', edit_todo_manager_path(todo_manager) %></td>
        <td><%= link_to 'Delete', todo_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Mark as Complete', complete_todo_manager_path(todo_manager), method: :patch %></td>
    </tr>
    <% count += 1 %>
    <% end %>
    <% end %>
</tbody>

</table>


<br>
<%= button_to 'New Todo Item', new_todo_manager_path, method: :get %>
<br><br>


<div>
Total todo items: <%= @todo_managers.size %>
</div>

app/views/todo_managers/new.html.erb
<div class = "todo_header">
<h1>New Todo Item</h1>
</div>
<%= render 'form', todo_manager: @todo_manager %>

<%= link_to 'Back', todo_managers_path %>

app/views/todo_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_manager.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_manager.description %>
</p>

<p>
  <strong>To be completed by:</strong>
  <%= @todo_manager.deadline %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @todo_manager.completed_at %>
</p>

<p>
  <strong>Completed ?</strong>
  <% if @todo_manager.completed %>
    <%= "Completed" %>
    <% else %>
    <%= "Not completed" %>
    <% end %>
</p>




<%= link_to 'Edit', edit_todo_manager_path(@todo_manager) %> |
<%= link_to 'Back', todo_managers_path %>